services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-PoemApp}
      MYSQL_USER: ${MYSQL_USER:-poemapp}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-poemapp}
      TZ : Asia/Shanghai
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: PoemApp.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=${MYSQL_DATABASE};User=root;Password=${MYSQL_ROOT_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Production
      - HostWebClient=false
      - Cors__AllowedOrigins=http://101.35.2.102:8080;http://localhost:8080;http://localhost:7000;http://localhost:5005
      - TZ=Asia/Shanghai
    depends_on:
      - db
    ports:
      - "5000:5000"

  admin:
    build:
      context: .
      dockerfile: PoemApp.Admin/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Production
      - Api__BaseUrl=http://api:5000
      - TZ=Asia/Shanghai
    depends_on:
      - api
    ports:
      - "7000:80"

  web:
    build:
      context: .
      dockerfile: PoemApp.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApiBaseUrl=http://101.35.2.102:5000/
      - TZ=Asia/Shanghai
    depends_on:
      - api
    ports:
      - "8080:80"

volumes:
  db_data:
